### ISSUE TITLE
XML are not being generated (NUnit Adapter)

### ISSUE THREAD

**Issue by Icaroto** [allure-framework/allure-nunit2#10]
Hi, I'm looking for a new way to create reports for my tests and I found out Allure solution. 

The problem is after run the tests there are no xml files being generated. 

I'm using NUnit 2.6.4. 
I added all the files of the Adapter (last version) to C:\Program Files (x86)\NUnit 2.6.4\bin\addins
Changed the config file to <results-path>C:\test-results\AllureResults</results-path>
And my nunit-x86.exe.config is: 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    
    <startup useLegacyV2RuntimeActivationPolicy="true">
        
    </startup>
    <runtime>
        
        <legacyUnhandledExceptionPolicy enabled="1"/>
        
        <loadFromRemoteSources enabled="true"/>
        
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <probing privatePath="lib;addins"/>
        </assemblyBinding>
    </runtime>
</configuration>

Am I forgetting something?

Thanks!

**Comment by ilya-murzinov** [comment]
@Icaroto hello.
You are using the wrong version of NUnit, try to use 2.6.3.

**Comment by Icaroto** [comment]
It works! Thanks @ilya-murzinov 

I kind have a few doubts now:

- First time I execute, it create the AllureResults folder and put all xml there. If I try to execute again, it will delete the AllureResults folder (with the results) and won't create a new one. So the second time I execute doesn't generate any files. Is that the properly behavior?

- Also, is there a way (using Visual Studio/Specflow) to add my own prints to the xml? Since the name is a random string, how can I access the right one to add my custom screenshot?

Thank you very much!!!

**Comment by ilya-murzinov** [comment]
Hi @Icaroto,
 1. Seems to be a bug.
 1. No, unfortunately, you can not add any attachments :(

**Comment by ilya-murzinov** [comment]
@Icaroto, by the way, now you can use 2.6.4, just make sure you are using the right adapter version for it.

**Comment by ken4ward** [comment]
I'm experiencing the same problem, i followed exactly as you requested him to work. To my surprise, it didn't work. What am I doing wrong?
