### ISSUE TITLE
Is it possible to convert nunit xml report to allure xml file manually? 

### ISSUE THREAD

**Issue by pashidlos** [allure-framework/allure-nunit2#12]
I'm using Nunit.Parallel (https://cpntr.codeplex.com/)
And I use ConsoleUnitTestsRunner command to run tests.
Unfortunately allure xml is not generated after :( 
But I have Nunit xml report.
Can I convert it manually to allure xml?

**Comment by ilya-murzinov** [comment]
Hi, @pashidlos!
I think the problem is that Nunit.Parallel uses unsupported NUnit version.
Do you know what version are they using?

Theoretically, you can convert NUnit xml report to allure xml with XSL transformation, but it's not quite that simple.
