### ISSUE TITLE
Query - screen shot on failure from remote server

### ISSUE THREAD

**Issue by aswhitehouse** [allure-framework/allure-nunit2#13]
Hi,
I'm using the framework and finding some queries along the way, I apologize if this is not really a bug but I feel that it would help people to have this documented to help future users setting up the FW.

I'm using Jenkins & selenium+Nunit and running tests on a remote server using remote web driver,
Because the Jenkins server is separate from the server that is executing the tests (the remote WD), the Allure screen shot action fails for obvious reasons with,

System.ComponentModel.Win32Exception : The handle is invalid
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)
   at AllureCSharpCommons.Utils.AllureResultsUtils.TakeScreenShot()
   at Foo.Config.AllureSteps.TestStepFail(String exception) in e:\foo\workspaces\TestAutomation\foo\staging\foo\Config\AllureSteps.cs:line 39
   at Foo.FooPages.FooActions.CheckLoggedInAccountIsSame(String expectedOutcome, String user) in 
...............

I'm think that the solution would be to use web driver's screen shot functionality for remote web driver to grab the screen shot which is reasonably straight forward, however I believe that to get it to work with Allure I'd have to generate the WD screen shot PNG file with the correct file ID, just like the Allure (AllureResultsUtils.TakeScreenShot()) method does,
Can you please shed some light on how this might work, or what's inside that method that names the image file correctly?
Would this solution even work?

AllureResultsUtils.TakeScreenShot() works perfectly when I'm running locally, but when I run remotely I'm thinking to implement this.

_lifeCycle.Fire(new StepFailureEvent());
var webDriver = new ScreenShotRemoteWebDriver(new Uri("http://foo/wd/hub"), DesiredCapabilities.Chrome());
var ss = ((ITakesScreenshot)webDriver).GetScreenshot();
var screenshot = ss.AsBase64EncodedString;
var screenshotAsByteArray = ss.AsByteArray;
ss.SaveAsFile("AllureResults/",ImageFormat.Png); <---------- Something to solve the file name for Allure
_lifeCycle.Fire(new TestCaseFailureEvent());
_lifeCycle.Fire(new TestCaseFinishedEvent());

**Comment by vania-pooh** [comment]
@ilya-murzinov any ideas?

**Comment by aswhitehouse** [comment]
Thanks vania,
There must be some code in that AllureResultsUtils.TakeScreenShot() method that applies a naming convention to the image file and then writes that name to the results xml as an attachment tag to the relevant test case.
EG-

</step>
        <step start="1429546991789" stop="1429546991789" status="passed">
          <name>Foo</name>
        </step>
      </steps>
      <attachments>
        <attachment title="Action failed" source="b0bec6d1e02fce45f977f2b1f680191384f8afa0cf1948aef62b0a485665de83-attachment.png" type="image/png" />
      </attachments>
    </test-case>
  </test-cases>
</test-suite>

Is it possible that the name of the file doesn't matter at all and more so that whatever ID I use needs to get written to the attachment tag section of that test suite's xml file?

If anyone knows how to guide me on this that would be great,
Will check back if I figure it out in the meantime.

Andrew.

**Comment by aswhitehouse** [comment]
@vania-pooh , @ilya-murzinov any ideas guys?

**Comment by vania-pooh** [comment]
@aswhitehouse probably, unfortunately I'm not a C# developer.

**Comment by aswhitehouse** [comment]
@vania-pooh , @ilya-murzinov 

No worries. I've come up with my own solution. Here it is in case it's useful to anyone else,
I had a look at the source code for the C# commons solution and it seems that the TakeScreenShot() method returns a byte array,

 public static byte[] TakeScreenShot()

return (byte[])........

I've written a web driver extension method to take a screen shot and return the output as a byte array, I can then substitute that for the Allure TakeScreenshot but still invoke the Allure "MakeAttachment" method and supply it with the screenshot from webdriver like so,

public static byte[] TakeADriverScreenShot(this IWebDriver driver, string fileLocationName,
            ImageFormat imageFormat)
        {
            var i = ((ITakesScreenshot)driver).GetScreenshot();
            var screenshotAsByteArray = i.AsByteArray;
            i.SaveAsFile("whatever.png", ImageFormat.Png);

            return screenshotAsByteArray;

        }

Then give this to the Allure MakeAttachment in lifecycle fail,

public void TestStepFail(string exception)
        {
            _lifeCycle.Fire(new StepFailureEvent());
            _lifeCycle.Fire(new MakeAttachmentEvent(Driver.TakeADriverScreenShot(@"C:\", System.Drawing.Imaging.ImageFormat.Bmp), exception,
                    "image/png"));
}


This is not particularly elegant at the moment and I need to tweak it,
Fortunately, this will take the screen shot and the MakeAttachment method will work as normal.

This should work with the remote web driver, however since the screen shot will get taken on the remote server (away from the Jenkins instance) I have to see if this is going to work for the originally intended issue.

Will report back when I've tested it thoroughly.


Cheers,

**Comment by aswhitehouse** [comment]
Works great on the remote server, images now showing up in the report on fail.

Cheers!

Andrew.

**Comment by ilya-murzinov** [comment]
@aswhitehouse, sorry I had no time to look into this, but you did great!
I think your solution can be very useful to other users.
It would be awesome if you could submit a pull-request with this.

**Comment by aswhitehouse** [comment]
@ilya-murzinov , no problem at all, happy if I can help anyone out.

Not sure what you want me to submit, given that my work around is simply writing an extension method for the web driver screen shot facility, and passing that into the normal Allure.MakeAttachment event, I'm not actually changing any of the Allure code for this,

Did I miss something here? Happy to do it if you let me know what you'd like, or I can just send you my code.

Thanks again, loving the report.

**Comment by BCR69** [comment]
@aswhitehouse Hello! I have a similar problem, but only in the case of TeamCity, which I was not able to find a solution. Your solution has brought the hope that I can use Allure. I would be very grateful if you could share more detailed your solution

**Comment by aswhitehouse** [comment]
@BCR69 , shouldn't matter what build client you're using but rather the architecture around where your tests run.
If your problem is the same as mine then you deploy to one server but run your tests on another via remote web driver. So the RWD has to report back the test assets to the deployment server in order for Allure to use them. For this reason the Allure take screenshot won't work.
What you need to do is write an extension method for take screenshot based on the one I provided above and use that instead of the allure core TS method. You can pretty much just copy paste my code and replace the references to the allure one in your project.
If this doesn't help let me know and I'll be happy to try and help you more

**Comment by BCR69** [comment]
@aswhitehouse I have published this issue https://github.com/allure-framework/allure-core/issues/548 , but I have not helped, because, as I understand, the support of the project on C# in Yandex no one does.
As I understand it, you have a similar problem. I also run tests remotely. 

I do not quite understand well your solution in terms of action sequences. Do I understand what I should to upload the source code of Allure to my project and use your method? At the current moment, I just copied library Allure directory to ..\NUnit 2.6.4\bin\addins

**Comment by aswhitehouse** [comment]
@BCR69 , I may create a pull request to core for this because it seems to be a common problem. But I can solve your issue right away.

You need to abstract the "take screenshot" method that allure does and replace it with my method I posted above. You don't need to have the allure core at all you just need to extend their method for take screenshot with mine. 
So what you do is you have an Allure "test case fail" step right? And that step uses the "take screenshot" allure method right?
Well, you just need to replace the allure "take screenshot" method with mine, which is exactly the same Type as theirs it's a byte array, so the allure step will accept. 
Just take a look at my TakeADriverScreenshot method I posted above, see how it returns a byte array but it references the remote web driver?
Copy paste that into a class in your project and reference the instance of WD you're using in your project, THEN, replace the Allure lifecycle "take screenshot" method in the "test case fail" Step with my TakeADriverScreenshot method, it won't complain because it's the same return type.

If that doesn't help I would be happy to share code and help you if you can show me your test case fail step? And how your remote web driver is configured.

Good luck.

**Comment by jonsteuwart** [comment]
@aswhitehouse I used your method and was able to create an attachment with screenshot. Now my question is: In the Allure results folder I see a new attachment gets created but in the Allure report it doesn't really attach it. How do I attach this screenshot attachment to that test case?

**Comment by aswhitehouse** [comment]
@jonsteuwart , can you check your test suite xml document that gets created in the report directory,
It should have an attachment tag and in that tag should reference the .png file you created. If that's not there then your allure step isn't attaching the file.
Don't forget you need to fire a test 'step' fail, do the make attachment event, and then fire test case failure event, followed by a test case finished event.
It sounds like you're triggering it correctly, but you may be missing an event somewhere.

**Comment by jonsteuwart** [comment]
@aswhitehouse Thanks for the response!
Here is my simple test. Again, I do see the attachment created in the Allure results folder but its not attached to this report for MyTest test case. Please advise what I am doing wrong here.

```
namespace Test
{
    [TestFixture]
    class Test
    {
        private Allure _lifecycle;
        public IWebDriver driver= new FirefoxDriver();

        [SetUp]
        public void Initialize()
        {
             driver.Navigate().GoToUrl("http://www.google.com");            
            _lifecycle = Allure.Lifecycle;
            _lifecycle.Fire(new TestSuiteStartedEvent("1", "TestSuite")
            {
                Labels = new[] { new label() }
            });
            _lifecycle.Fire(new TestCaseStartedEvent("1", "Test Case ID: 1")
            {
                Labels = new[] { new label() }
            });
            _lifecycle.Fire(new StepStartedEvent("1"));
        }
        
        
        [TestCase]
        public void MyTest()
        {
            try
            {
                Assert.AreEqual(0, 1);
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception was caught here : "+e);
                _lifecycle.Fire(new StepFailureEvent());
                _lifecycle.Fire(new MakeAttachmentEvent(driver.TakeAScreenShot(
                               @"C:\",
                               System.Drawing.Imaging.ImageFormat.Bmp
                     ), e.StackTrace, "image/png"));
                _lifecycle.Fire(new TestCaseFailureEvent());
                _lifecycle.Fire(new StepFinishedEvent());
                _lifecycle.Fire(new TestCaseFinishedEvent());
                _lifecycle.Fire(new TestSuiteFinishedEvent("1"));
            }
            
        }

    }
}

```

 @ilya-murzinov FYI to see if you have any inputs.

**Comment by aswhitehouse** [comment]
Hey,

This is what I get when I copy paste your code into a blank solution (obviously after resolving my own using statements)

I run the test I get the image creation and I get the attachment tag in my report,

EG -

<?xml version="1.0"?>
<test-suite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" start="1441213509445" stop="1441213540320" version="1.4.0" xmlns="urn:model.allure.qatools.yandex.ru">
  <name xmlns="">TestSuite</name>
  <test-cases xmlns="">
    <test-case start="1441213509461" stop="1441213539492" status="broken">
      <name>Test Case ID: 1</name>
      <failure>
        <message>Test broken with unknown reason</message>
      </failure>
      <steps>
        <step start="1441213509477" stop="1441213533087" status="broken">
          <name>1</name>
        </step>
      </steps>
      <attachments>
        <attachment title="   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)&#xD;&#xA;   at NUnit.Framework.Assert.AreEqual(Int32 expected, Int32 actual)&#xD;&#xA;   at debug.Class1.MyTest() in c:\foo source="97887ec813f728fae4d305f5c2311af40cdd603bcd84b88a35357f72d468edcf-attachment.png" type="image/png" />
      </attachments>
      <labels>
        <label />
      </labels>
    </test-case>
  </test-cases>
  <labels xmlns="">
    <label />
  </labels>
</test-suite>




What version of the framework are you using, the latest from Nuget?

**Comment by aswhitehouse** [comment]
just one more thing, where do you specify your report path? where are the outputs getting stored?

**Comment by jonsteuwart** [comment]
@aswhitehouse 

The location where the XML and screenshot get saved is C:\AllureResults\
The location where the actual Allure report gets saved is C:\AllureResults\allure-report

.Net framework 4.0
AllureCSharpCommons version 0.1.0.29896

Here is the XML:

```
<?xml version="1.0"?>
<test-suite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" start="1441185918646" stop="1441185919013" version="1.4.0" xmlns="urn:model.allure.qatools.yandex.ru">
  <name xmlns="">TestSuite</name>
  <test-cases xmlns="">
    <test-case start="1441185918646" stop="1441185919013" status="broken">
      <name>Test Case ID: 1</name>
      <failure>
        <message>Test broken with unknown reason</message>
      </failure>
      <steps>
        <step start="1441185918647" stop="1441185919013" status="broken">
          <name>1</name>
        </step>
      </steps>
      <attachments>
        <attachment title="   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)&#xD;&#xA;   at Test.MyTest() in c:\Project\Test.cs:line 47" source="484f96e8d4ea27105ee86926a49897a5e17d15dc0ae172f9794f3ab56251a189-attachment.png" type="image/png" />
      </attachments>
      <labels>
        <label />
      </labels>
    </test-case>
  </test-cases>
  <labels xmlns="">
    <label />
  </labels>
</test-suite>

```
@aswhitehouse 
Also on another note, My report start time and finished time are 3hrs  ahead of my time. Not sure how to configure that.

Thanks for your help mate!

**Comment by aswhitehouse** [comment]
@jonsteuwart , The file is correctly attached to the report so your code and your report XML are all correct, there must be another reason for it not showing.

How are you actually viewing your report are you using a CI server plugin or are you just running the command line tool and viewing it through a browser locally?

What actually happens when you open up the report and look at the test case tab, is there a broken image link in there or just nothing?
I'm pretty sure the assets all need to be in the same directory as it doesn't specify path, just file name, can you try dropping the image into the same folder as the report?

Since it doesn't appear to be a back end problem it's hard without seeing your actual setup.

**Comment by jonsteuwart** [comment]
@aswhitehouse 
Everything is on my local and using CLI command line for allure report. All the artifacts are in the folder that uses it to create the report. So no issues there. Nothing is broken in the report and as you mentioned, I do get the attachment into my report now. But the only problem is its under TestSuite and not under the Test that made this attachment. If I remove the TestSuite attribute as listed above and just have the _lifecycle.Fire(new MakeAttachmentEvent), it does n't even show up on the report.

So, Is this how Allure has implemented? That you have to have a test suite in order to attach anything to the Test? Can I not have a plain lifecycle and just attach it?

Also, It would be helpful if you could provide your own example that works for ya.

**Comment by aswhitehouse** [comment]
Here's an example of how I do mine, sorry just only have time to post this right now.

```
[TestFixtureSetUp]
        public void Setup()
        {
            _lifeCycle = Allure.Lifecycle;
            Steps = new AllureSteps();
            Steps.TestSuiteStart("RegressionTest", "ApplicationName - Shopping Cart Test Suite");
        }
        [TestFixtureTearDown]
        public new void TearDown()
        {
            Steps.TestSuiteFinish("RegressionTest");
        }
        [Test]
        public void AsAUser_WhoDoesSomeAction_ActionSuccess()
        {
            Steps.TestCaseStart("RegressionTest", "AsAUser_WhoDoesSomeAction_ActionSuccess");
            // DO TESTING.......
            Steps.TestCaseFinish();
        }
```

**Comment by Mritunjay1996** [comment]
@aswhitehouse can you help me out with adding screenshot in allure report.
