### ISSUE TITLE
Allure parameter (example:Allurefeature,AllureSeverity) is missing in the output xml and in the report

### ISSUE THREAD

**Issue by pdoggyster** [allure-framework/allure-nunit2#14]
When I use the Valuesource in the tests and I add some own allure parameter to the tests then the parameter is missing in the output xml.

**Comment by pdoggyster** [comment]
AllureEventListener.cs implements TestStarted method, which has a line to determine the actual method's name:
string clazz = testName.FullName.Split('.')[testName.FullName.Split('.').Count() - 2];
In case of using valuesource and providing any value containing dots (domain name, ip address, string with dots), the test case name cannot be calculated properly.
Suggestion: when initalizing the test case name, be aware of generated methods and do the same check as you do later when getting members ( !testName.Name.Contains("(") )

**Comment by ilya-murzinov** [comment]
Hi, @pdoggyster!
Can you please submit a pull-request with workaround for this?

**Comment by pdoggyster** [comment]
Hi,
Sorry for the late answer. I can't submit but I add it here:
Old code in the AllureEventListener.cs
```
                string clazz = testName.FullName.Split('.')[testName.FullName.Split('.').Count() - 2];
```
New code:
```
                string polished = !testName.FullName.Contains("(")
                           ? testName.FullName
                           : testName.FullName.Substring(0, testName.FullName.IndexOf('('));
                string clazz = polished.Split('.')[polished.Split('.').Count() - 2];
