### ISSUE TITLE
AllureResults folder is not created after tests run(C# + NUnit 2.6.3 + allure-nunit2)

### ISSUE THREAD

**Issue by yknyshich** [allure-framework/allure-nunit2#24]
Hello,

I want to integrate reporting in my Specflow project. I followed the steps [here](https://github.com/allure-framework/allure-nunit2) and report was generated only in the first time. Now, every time I run the test from console, 'AllureResults' folder with xml files inside is not generated. I put allure-nunit2 binaries this way https://i.imgur.com/2sZk2pM.png 
I tried to use both NUnit 2.6.3 + allure-nunit2 v0.2.0 and NUnit 2.6.4 + allure-nunit2 v0.2.1, but it still failing.

Could you say, please, what is possible reason for this and how it could be resolved?

Thanks in advance

**Comment by Bakanych** [comment]
Hi @yana178,
have you tried [specflow plugin](https://github.com/allure-framework/allure-specflow) for allure?
You can just add nuget package to your test project.

**Comment by yana178** [comment]
Hello @Bakanych. Thanks for your reply. I read about this plugin, but I am looking for universal approach, which I may use in both BDD and non-BDD projects. I saw the post with a similar issue there, maybe somebody has managed to resolve it?

**Comment by KursLabIgor** [comment]
I have same issue no reports. And i dont want include any other dll to project. I need to get report based on xml.

**Comment by jkwaldrip** [comment]
Are there any updates on this issue?

**Comment by Bakanych** [comment]
Hi @jkwaldrip 
This repo is not supported at this moment. Can you please try to use this implementation?
https://github.com/unickq/allure-nunit
