### ISSUE TITLE
Missing Test Cases for Some Tests - Allure Test Report

### ISSUE THREAD

**Issue by ilya-murzinov** [allure-framework/allure-nunit2#9]
@raj84:

> I am using nunitadapter to generate the xml output. Then using the Allure Jenkins plugin to generate the report. The report is generated (report version 1.4.5). All tests are displayed.
> 
> For some tests, a couple of test cases are missing.
> 
> In Jenkins, if I navigate to the TestResults folder for the build, I am able to see all the test cases listed for a particular test (a total of 8 test cases). In Allure for the same test, I am able to see only 2 test cases.
> 
> This issue is happening across multiple tests. Jenkins Test Results folder is saying that there are a total of 266 test cases. Allure report says a total of 241 test cases.

See [this issue](https://github.com/allure-framework/allure-core/issues/466) for details.

**Comment by ilya-murzinov** [comment]
@raj84, which version of the adapter are you using?

**Comment by ilya-murzinov** [comment]
@raj84, also, can you please provide an example project that I can use to reproduce this behavior?

**Comment by raj84** [comment]
Thanks a lot for creating an issue to investigate this issue.

Adapter version: 0.2.0 (says latest version on the page)

what do you mean by example project? Do you mean the the test file?

**Comment by ilya-murzinov** [comment]
@raj84, that's weird, I thought I fixed same bug in 0.1.0..
By example project I mean a project containing tests, some of which are not present in output XML.
Because when I run tests on some of my projects, output XML contains all tests, so I can't reproduce this problem.

Also, can you please decribe, how EXACTLY you run these tests? You mentioned Jenkins, do you use **nunit-console** as a build step in Jenkins?

**Comment by raj84** [comment]
Yes, I am using nunit-console as a build step in Jenkins 

"%DOTCOVER_PATH%\dotCover.exe" analyse "/TargetExecutable=C:\Program Files (x86)\NUnit 2.6.3\bin\nunit-console.exe" "/Filters=-:*.Tests;+:assembly=*" "/ReportType=HTML" "/AttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" "/Output=cover-output.HTML" "/TargetArguments=%nunitFiles% /xml=%WORKSPACE%\nunit-output.xml /timeout:300000 /noshadow"

**Comment by raj84** [comment]
This test case is present in the output xml. You can refer to the screenshot I had attached under ***NOT WORKING****

[Test]
		public void TestReadAverageLine()
		{
			var lines = this.SetUpLines();
			var service = this.Get<TrendChartLineProvider>();
			var line = service.ReadTrendChartLine(lines.Single(l => l.Type == TrendChartLineType.Average).TrendChartLineId);
			line.Points.Select(p => new { p.Sequence, p.Lift })
				.SequenceShouldEqual(new[] { new { Sequence = 1.0, Lift = (double?)5.0 }, new { Sequence = 3.0, Lift = (double?)5.0 } }, RecordComparer.CreateFor(new { Sequence = default(double), Lift = default(double?) }));
		}
		
I dont want to paste in all the 6 test cases that dont show up on the xml output because they are all somewhat similar. I am providing 2 test cases that dont show up on the generated xml 

[Test]
		public void TestReadRegressionLine([Values(true, false)] bool isTrendLineExtended)
		{
			var lines = this.SetUpLines(isTrendLineExtended: isTrendLineExtended);
			var service = this.Get<TrendChartLineProvider>();
			var line = service.ReadTrendChartLine(lines.Single(l => l.Type == TrendChartLineType.Regression).TrendChartLineId);

			var expectedFirstPoint = isTrendLineExtended
				? new { Sequence = -4.0, Lift = (double?)492 }
				: new { Sequence = -3.0, Lift = (double?)494 };

			line.Points.Select(p => new { p.Sequence, p.Lift })
				.SequenceShouldEqual(new[] { expectedFirstPoint, new { Sequence = -1.0, Lift = (double?)498 } }, RecordComparer.CreateFor(new { Sequence = default(double), Lift = default(double?) }));
		}



[Test]
		public void TestReadPrePeriodTrendLine()
		{
			var lines = this.SetUpLines(trendLineIsPreOnly: true);
			var service = this.Get<TrendChartLineProvider>();
			var line = service.ReadTrendChartLine(lines.Single(l => l.Type == TrendChartLineType.Trend).TrendChartLineId);
			line.Points.Select(p => p.Lift.Value)
				.SequenceShouldEqual(new double[] { -40, -30, -20, -10 }, UnitTestHelpers.GetDoubleComparer(1e-9));
		}

**Comment by ilya-murzinov** [comment]
@raj84, actually I'm not interested in source code of tests, I just need compiled **\*.dll** file to run test from it.
Since I suppose you can't provide compiled assembly of you project I ask you to try to create another simple project on which I can reproduce this problem with missing tests in report.

**Comment by raj84** [comment]
@ilya-murzinov I will work on this and will provide you a compiled *.dll as soon as I can. Thanks once again

**Comment by ilya-murzinov** [comment]
That would be a great help, thanks!

**Comment by ilya-murzinov** [comment]
@raj84 how is it going? Are you still experiencing troubles?

**Comment by portlandia** [comment]
We also noticed some missing test cases, and suspect that it might have something to do with the test case name containing parenthesis. The parenthesis in our tests are generated by Nunit during test execution. Does this sound like it could cause problems with allure-nunit2? Or is this perhaps an known issue with the Allure Jenkins plugin?
